MODEL:
  NAME: 'pose_resnet'
  PRETRAINED: 'models/pytorch/imagenet/resnet50-19c8e357.pth'
  IMAGE_SIZE:
  - 192
  - 256
  NUM_JOINTS: 17
  EXTRA:
    TARGET_TYPE: 'gaussian'
    HEATMAP_SIZE:
    - 48
    - 64
    SIGMA: 2
    FINAL_CONV_KERNEL: 1
    DECONV_WITH_BIAS: false
    NUM_DECONV_LAYERS: 3
    NUM_DECONV_FILTERS:
    - 256
    - 256
    - 256
    NUM_DECONV_KERNELS:
    - 4
    - 4
    - 4
    NUM_LAYERS: 50